# Generated by Django 3.2.7 on 2021-10-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211002_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='text',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='title',
        ),
    ]
