# Generated by Django 3.2.7 on 2021-10-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_memo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='image',
        ),
        migrations.AddField(
            model_name='memo',
            name='breakfast',
            field=models.ImageField(blank=True, null=True, upload_to='images/breakfast/%Y/%m/%d/%s/'),
        ),
        migrations.AddField(
            model_name='memo',
            name='breakfastEvaluation',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='memo',
            name='breakfastName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='memo',
            name='dinner',
            field=models.ImageField(blank=True, null=True, upload_to='images/dinner/%Y/%m/%d/%s/'),
        ),
        migrations.AddField(
            model_name='memo',
            name='dinnerEvaluation',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='memo',
            name='dinnerName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='memo',
            name='lunch',
            field=models.ImageField(blank=True, null=True, upload_to='images/lunch/%Y/%m/%d/%s/'),
        ),
        migrations.AddField(
            model_name='memo',
            name='lunchEvaluation',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='memo',
            name='lunchName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='memo',
            name='mealComment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='snack',
            field=models.ImageField(blank=True, null=True, upload_to='images/snack/%Y/%m/%d/%s/'),
        ),
        migrations.AddField(
            model_name='memo',
            name='snackEvaluation',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='memo',
            name='snackName',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
