# Generated by Django 3.2.7 on 2021-10-26 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211016_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='dateData',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
